#!/bin/bash
 #RB
# This first command will output all pf netstat into a single txt file(networkdumpONE-_-3-3-22.txt)
echo `netstat -a;`>networkdumpONE-_-3-3-22.txt  


#This second command will output all of rout into the secoud txt file (networkdumpTWO-_-3-3-22.txt)
 
echo `route -e;`>networkdumpTWO-_-3-3-22.txt  



#This command will dump all of ip config into the third txt filed called (networkdumpTHREE-_-3-3-22.txt)
echo `ifconfig;`>networkdumpTHREE-_-3-3-22.txt

#My DNS Server IP Address
echo `cat /etc/resolv.conf;`>YourDNS-_-3-3-22.txt

#My ARP table
echo `arp -e;`>YourARPTABLE-_-3-3-22.txt

#at the end this command will print complete meanig that it has created all three file
echo "Your Network has Been dUMP into three diffrent txt files,My DNS Server IP Address and arp table"

# i decieded to make three txt file to ease reading
